using System.Text;

namespace JJFlexWpf.Tests.Infrastructure;

/// <summary>
/// Turns a sweep into the inventory document.
///
/// <para>Prose and bullets only, never a table. The person who reads this reads
/// it with a screen reader, and a table of findings is a table he has to
/// navigate cell by cell to learn anything.</para>
/// </summary>
public static class ReportWriter
{
    public static string Build(IReadOnlyList<DialogReport> reports, IReadOnlyList<ProbeResult>? probes, IReadOnlyList<DelegateSurface> surfaces)
    {
        var sb = new StringBuilder();
        var inspected = reports.Where(r => !r.Skipped).ToList();
        var skipped = reports.Where(r => r.Skipped).ToList();
        var findings = inspected.SelectMany(r => r.Findings).ToList();

        sb.AppendLine("# Tier 1 invariant sweep - findings inventory");
        sb.AppendLine();
        sb.AppendLine($"Generated by `JJFlexWpf.Tests` on {DateTime.Now:yyyy-MM-dd HH:mm}. ");
        sb.AppendLine("This file is written by the suite, not by hand. Re-run the tests to regenerate it.");
        sb.AppendLine();
        sb.AppendLine("Findings are reported, not fixed. Each one names the dialog, the control and the invariant it breaks.");
        sb.AppendLine();

        sb.AppendLine("## Coverage");
        sb.AppendLine();
        sb.AppendLine($"- Dialogs inspected: {inspected.Count}");
        sb.AppendLine($"- Dialogs skipped: {skipped.Count}");
        sb.AppendLine($"- Total findings: {findings.Count}");
        sb.AppendLine($"- Dialogs with at least one finding: {inspected.Count(r => r.Findings.Count > 0)}");
        sb.AppendLine($"- Automation peers walked: {inspected.Sum(r => r.PeerCount)}");
        sb.AppendLine($"- Focusable controls seen: {inspected.Sum(r => r.FocusableCount)}");
        sb.AppendLine();

        AppendIsolation(sb);

        if (probes is { Count: > 0 })
        {
            sb.AppendLine("## Focus-avoidance strategies, measured");
            sb.AppendLine();
            sb.AppendLine("Each candidate strategy was run against a plain dialog, the Settings dialog and the Audio Workshop.");
            sb.AppendLine();
            foreach (var strategy in probes.Select(p => p.Strategy).Distinct())
            {
                sb.AppendLine($"### {strategy}");
                sb.AppendLine();
                foreach (var probe in probes.Where(p => p.Strategy == strategy))
                {
                    var note = string.IsNullOrWhiteSpace(probe.Note) ? string.Empty : " " + probe.Note;
                    sb.AppendLine(
                        $"- {probe.Dialog}: constructed {YesNo(probe.Constructed)}, Loaded fired {YesNo(probe.LoadedFired)}, " +
                        $"{probe.PeerCount} automation peers, {probe.FocusableCount} focusable controls, " +
                        $"focus movable {YesNo(probe.FocusMovable)}, {probe.TabStops} tab stops.{note}");
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("## Findings by invariant");
        sb.AppendLine();
        foreach (var invariant in Enum.GetValues<Invariant>())
        {
            var group = findings.Where(f => f.Invariant == invariant).ToList();
            sb.AppendLine($"### Invariant {(int)invariant} - {Describe(invariant)}");
            sb.AppendLine();
            if (group.Count == 0)
            {
                sb.AppendLine("No findings.");
                sb.AppendLine();
                continue;
            }

            sb.AppendLine($"{group.Count} finding(s) across {group.Select(f => f.Dialog).Distinct(StringComparer.Ordinal).Count()} dialog(s).");
            sb.AppendLine();
            foreach (var byDialog in group.GroupBy(f => f.Dialog, StringComparer.Ordinal).OrderBy(g => g.Key, StringComparer.Ordinal))
            {
                sb.AppendLine($"- **{byDialog.Key}**");
                foreach (var finding in byDialog)
                    sb.AppendLine($"  - {finding.Control}: {finding.Detail}");
            }
            sb.AppendLine();
        }

        if (surfaces.Count > 0)
        {
            var dead = surfaces.Where(s => s.IsDeadSurface).ToList();
            sb.AppendLine("### Invariant 7 - no dead delegate surface");
            sb.AppendLine();
            sb.AppendLine("A hook that is declared, called from a real callsite, and never assigned anywhere in the worktree. ");
            sb.AppendLine("The menu item exists, the call happens, and nothing occurs. There is no window to walk, which is why ");
            sb.AppendLine("this one class of dead surface is confirmed from the callsites instead of from a tree.");
            sb.AppendLine();
            if (dead.Count == 0)
            {
                sb.AppendLine("No findings.");
            }
            else
            {
                foreach (var surface in dead)
                {
                    sb.AppendLine($"- **{surface.Name}** declared at {surface.DeclaredIn}, never assigned.");
                    foreach (var callsite in surface.InvokedFrom)
                        sb.AppendLine($"  - called from {callsite}");
                }
            }
            sb.AppendLine();
        }

        sb.AppendLine("## Dialogs skipped, with reasons");
        sb.AppendLine();
        if (skipped.Count == 0)
        {
            sb.AppendLine("None.");
        }
        else
        {
            foreach (var report in skipped)
                sb.AppendLine($"- **{report.Dialog}**: {report.SkipReason}");
        }
        sb.AppendLine();

        sb.AppendLine("## Dialogs inspected, clean");
        sb.AppendLine();
        var clean = inspected.Where(r => r.Findings.Count == 0).Select(r => r.Dialog).ToList();
        sb.AppendLine(clean.Count == 0 ? "None." : string.Join(", ", clean) + ".");
        sb.AppendLine();

        sb.AppendLine("## Per-dialog detail");
        sb.AppendLine();
        foreach (var report in inspected.OrderByDescending(r => r.Findings.Count).ThenBy(r => r.Dialog, StringComparer.Ordinal))
        {
            sb.AppendLine(
                $"- **{report.Dialog}**: {report.PeerCount} peers, {report.FocusableCount} focusable, {report.TabStopCount} tab stops, " +
                $"Loaded {(report.LoadedFired ? "fired" : "did NOT fire")}, {report.Findings.Count} finding(s)." +
                (report.FocusWalkDiagnostic != null ? " Focus walk: " + report.FocusWalkDiagnostic : string.Empty));
        }
        sb.AppendLine();

        return sb.ToString();
    }

    private static string YesNo(bool value) => value ? "yes" : "no";

    /// <summary>
    /// On what grounds this run was allowed to build windows, and whether it
    /// could be heard.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Task #233.</b> <c>UiThread.Isolation</c> and <c>UiThread.Guard</c>
    /// were surfaced in no run report at all — <c>Isolation</c> appeared only
    /// inside a comment in <c>Sweep.cs</c>. So an allowed run never stated on
    /// what grounds it was allowed, and afterwards "properly isolated" looked
    /// identical to "somebody waived the check". That absence is how a failing
    /// isolation went unnoticed in the first place, and it is why the audio
    /// state is stated here from the beginning rather than added later.
    /// </para>
    /// <para>
    /// It is written even when everything is fine. A line that only appears on
    /// failure teaches the reader to skip it, and the question this answers —
    /// "should I have heard anything?" — is one an operator asks after a
    /// perfectly ordinary run.
    /// </para>
    /// </remarks>
    private static void AppendIsolation(StringBuilder sb)
    {
        sb.AppendLine("## How this run was allowed");
        sb.AppendLine();
        sb.AppendLine($"- Windows: {DeskGuard.Describe(UiThread.Guard)}");
        sb.AppendLine($"- Desktop isolation: {UiThread.Isolation}" +
                      (UiThread.Isolation is DesktopIsolation.CreateFailed or DesktopIsolation.SwitchFailed
                          ? $" (Windows error {PrivateDesktop.LastError})"
                          : string.Empty));
        sb.AppendLine($"- Sound: {QuietRun.Describe()}");
        sb.AppendLine($"- Settings: {TestSettingsRoot.Describe()}");
        sb.AppendLine();
        sb.AppendLine("Sight, sound and settings are three separate facts and all three are stated. " +
                      "A run can be invisible and still be heard, which for this project's users is the " +
                      "worse of the two failures: a sound that arrives from something that cannot be " +
                      "found, focused or dismissed. And it can be both invisible and silent while still " +
                      "rewriting the operator's own configuration, which is the failure that outlasts " +
                      "the run — this tier constructs every dialog in the app, and a dialog reads and " +
                      "rewrites configuration as it builds itself.");
        sb.AppendLine();
    }

    private static string Describe(Invariant invariant) => invariant switch
    {
        Invariant.FocusableHasName => "every focusable control exposes a non-empty automation Name",
        Invariant.AutomationSubtreeComplete => "nothing focusable is missing from the automation tree, and no peer throws while being walked",
        Invariant.HelpTextNotEmpty => "every control that declares help text actually has some",
        Invariant.FocusConserved => "focus cycles are conserved",
        Invariant.UniqueAutomationIds => "no duplicate automation ids within one window",
        Invariant.KeyboardReachable => "every actionable control is reachable from the keyboard",
        Invariant.NoDeadDelegateSurface => "no surface is wired to a delegate that nothing ever assigns",
        _ => invariant.ToString(),
    };
}
