Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices

' Non-version assembly attributes live here. The version attributes
' (AssemblyVersion / AssemblyFileVersion / AssemblyInformationalVersion)
' are generated by the SDK from the <Version> property in JJFlexRadio.vbproj,
' which build-installers.bat overrides on the command line with a
' monotonic 4-part value (git commit count + offset). Do NOT re-add
' version attributes here — duplicates will fail the build.

<Assembly: AssemblyTitle("JJ Flexible Radio Access")>
<Assembly: AssemblyDescription("Amateur Radio control for blind Flex Radio users")>
<Assembly: AssemblyCompany("JJShaffer.com")>
<Assembly: AssemblyProduct("JJ Flexible Radio Access")>
<Assembly: AssemblyCopyright("J.J. Shaffer, Noel Romey 2019-2025 (GNU GPL)")>
<Assembly: AssemblyTrademark("")>

<Assembly: ComVisible(False)>

'The following GUID is for the ID of the typelib if this project is exposed to COM
<Assembly: Guid("f6a1af9f-ca41-4a8c-94dc-a3687b55c4b6")>
